const state={songs:[],edges:[],mode:'compare',positions:{},filter:'',album:''};
const $=s=>document.querySelector(s); const canvas=$('#canvas');
async function load(){[state.songs,state.edges]=await Promise.all([fetch('/api/songs').then(r=>r.json()),fetch('/api/connections').then(r=>r.json())]); fillAlbums(); fillFormSongs(); render();}
function fillAlbums(){const select=$('#album');[...new Set(state.songs.map(s=>s.album))].forEach(a=>select.add(new Option(a,a)))}
function fillFormSongs(){document.querySelectorAll('select[name=source_id],select[name=target_id]').forEach(select=>state.songs.forEach(s=>select.add(new Option(`${s.title} · ${s.album}`,s.id))))}
function visibleSongs(){return state.songs.filter(s=>(!state.filter||`${s.title} ${s.album}`.toLowerCase().includes(state.filter))&&(!state.album||s.album===state.album))}
function visibleEdges(){return state.edges.filter(e=>state.mode==='compare'||e.kind===state.mode).filter(e=>visibleSongs().some(s=>s.id===e.source_id)&&visibleSongs().some(s=>s.id===e.target_id))}
function pos(id,i){if(!state.positions[id]){const cols=5;state.positions[id]={x:35+(i%cols)*155,y:30+Math.floor(i/cols)*82}}return state.positions[id]}
function render(){canvas.innerHTML='';const songs=visibleSongs(), edges=visibleEdges();songs.forEach((s,i)=>{const p=pos(s.id,i),n=document.createElement('button');n.className='node';n.style.left=p.x+'px';n.style.top=p.y+'px';n.dataset.id=s.id;n.innerHTML=`${s.title}<small>${s.album}</small>`;n.onclick=()=>showSong(s);drag(n,s.id);canvas.append(n)});edges.forEach(e=>{const a=pos(e.source_id,songs.findIndex(s=>s.id===e.source_id)),b=pos(e.target_id,songs.findIndex(s=>s.id===e.target_id));const line=document.createElement('div');line.className=`edge ${e.kind}`;const dx=b.x-a.x,dy=b.y-a.y;line.style.left=(a.x+59)+'px';line.style.top=(a.y+25)+'px';line.style.width=Math.hypot(dx,dy)+'px';line.style.transform=`rotate(${Math.atan2(dy,dx)}rad)`;canvas.prepend(line)});$('#count').textContent=`${songs.length} songs · ${edges.length} visible connections`}
function drag(node,id){let moving=false,ox,oy;node.onpointerdown=e=>{moving=true;node.setPointerCapture(e.pointerId);ox=e.clientX-node.offsetLeft;oy=e.clientY-node.offsetTop};node.onpointermove=e=>{if(!moving)return;const x=Math.max(0,e.clientX-ox),y=Math.max(0,e.clientY-oy);state.positions[id]={x,y};node.style.left=x+'px';node.style.top=y+'px'};node.onpointerup=()=>{moving=false;render()}}
function showSong(song){const related=state.edges.filter(e=>e.source_id===song.id||e.target_id===song.id);$('#songDetail').innerHTML=`<p class="detail-meta">${song.album}</p><h2>${song.title}</h2><p class="muted">Lyrics are intentionally not bundled. Add an approved lyrics source when the analysis pipeline is connected.</p>${related.length?related.map(e=>{const other=state.songs.find(s=>s.id===(e.source_id===song.id?e.target_id:e.source_id));return `<div class="connection"><strong>${other.title}</strong><br><em>${e.kind==='ai'?'AI analysis':'Human note'}: ${e.note}</em></div>`}).join(''):'<p class="muted">No connections yet.</p>'}`;$('#songDialog').showModal()}
$('.close').onclick=e=>e.target.closest('dialog').close();$('#addBtn').onclick=()=>$('#connectionDialog').showModal();document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-mode]').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.mode=b.dataset.mode;render()});$('#search').oninput=e=>{state.filter=e.target.value.toLowerCase();render()};$('#album').onchange=e=>{state.album=e.target.value;render()};$('#connectionForm').onsubmit=async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target));data.source_id=+data.source_id;data.target_id=+data.target_id;const r=await fetch('/api/connections',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});if(!r.ok){$('#formError').textContent=(await r.json()).detail||'Could not publish.';return}state.edges.push(await r.json());e.target.reset();$('#connectionDialog').close();render()};load();
